import { SpellId } from "./types";
import SPELLS from "./spells";
import TALENTS from "./talents";
import COVENANT_SPELLS from "./covenant-spells";

const spells: ReadonlyArray<SpellId | SpellId> = [
  TALENTS.PALADIN.HOLY_AVENGER_TALENT.id,
  TALENTS.PALADIN_HOLY.AVENGING_CRUSADER_TALENT.id,
  SPELLS.PALADIN_HOLY.AURA_MASTERY.id,
  SPELLS.PALADIN.AVENGING_WRATH.id,
  COVENANT_SPELLS.PALADIN.VENTHYR.ASHEN_HALLOW.id,

  SPELLS.PRIEST_DISCIPLINE.POWER_WORD_BARRIER_CAST.id,
  TALENTS.PRIEST_DISCIPLINE.EVANGELISM_TALENT.id,
  TALENTS.PRIEST_DISCIPLINE.SPIRIT_SHELL_TALENT.id,
  TALENTS.PRIEST_DISCIPLINE.SCHISM_TALENT.id,
  SPELLS.PRIEST_DISCIPLINE.SHADOWFIEND.id,
  SPELLS.PRIEST_DISCIPLINE.RAPTURE.id,
  SPELLS.PRIEST_DISCIPLINE.POWER_WORD_RADIANCE.id,

  SPELLS.SHAMAN_RESTORATION.HEALING_TIDE_TOTEM_CAST.id,
  SPELLS.SHAMAN_RESTORATION.SPIRIT_LINK_TOTEM.id,
  SPELLS.SHAMAN_RESTORATION.ASCENDANCE_HEAL.id,
  TALENTS.SHAMAN_RESTORATION.ANCESTRAL_PROTECTION_TOTEM_TALENT.id,

  TALENTS.DRUID.HEART_OF_THE_WILD_TALENT.id,
  SPELLS.DRUID_RESTORATION.TRANQUILITY_CAST.id,
  TALENTS.DRUID_RESTORATION.INCARNATION_TREE_OF_LIFE_TALENT.id,
  TALENTS.DRUID_RESTORATION.FLOURISH_TALENT.id,
  COVENANT_SPELLS.DRUID.NIGHT_FAE.CONVOKE_SPIRITS.id,

  SPELLS.MONK_MISTWEAVER.REVIVAL.id,
  TALENTS.MONK_MISTWEAVER.INVOKE_CHI_JI_THE_RED_CRANE_TALENT.id,
  COVENANT_SPELLS.MONK.KYRIAN.WEAPONS_OF_ORDER_CAST.id,

  TALENTS.PRIEST_HOLY.HOLY_WORD_SALVATION_TALENT.id,
  TALENTS.PRIEST_HOLY.APOTHEOSIS_TALENT.id,
  SPELLS.PRIEST_HOLY.DIVINE_HYMN_CAST.id,

  SPELLS.WARRIOR.RALLYING_CRY.id,
  SPELLS.DEATHKNIGHT.ANTI_MAGIC_ZONE.id,
  SPELLS.DEMONHUNTER_HAVOC.DARKNESS.id,
  SPELLS.PRIEST_SHADOW.VAMPIRIC_EMBRACE.id,
  TALENTS.SHAMAN_ELEMENTAL.ANCESTRAL_GUIDANCE_TALENT.id,
  SPELLS.SHAMAN.BLOODLUST.id,

  SPELLS.SHARED.PERSONALS.id,
];
export default spells;
