import { RosterCharacter, RosterCharacterId } from "types";
import { v4 as uuidv4 } from "uuid";
import DB from "@cdplan/db";
import randomNames from "./randomNames";

const randomRoster: RosterCharacter[] = [
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[0],
    covenant: DB.COVENANTS.KYRIAN,
    pclass: DB.CLASSES.DEMONHUNTER,
    spec: DB.SPECS.DEMONHUNTER_VENGEANCE,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[1],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.DRUID,
    spec: DB.SPECS.DRUID_GUARDIAN,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[2],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.WARRIOR,
    spec: DB.SPECS.WARRIOR_FURY,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[3],
    covenant: DB.COVENANTS.NECROLORD,
    pclass: DB.CLASSES.DEATHKNIGHT,
    spec: DB.SPECS.DEATHKNIGHT_UNHOLY,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[4],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.DRUID,
    spec: DB.SPECS.DRUID_BALANCE,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[5],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.DRUID,
    spec: DB.SPECS.DRUID_BALANCE,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[6],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.HUNTER,
    spec: DB.SPECS.HUNTER_MARKSMANSHIP,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[7],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.HUNTER,
    spec: DB.SPECS.HUNTER_BEASTMASTERY,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[8],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.MAGE,
    spec: DB.SPECS.MAGE_FIRE,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[9],
    covenant: DB.COVENANTS.VENTHYR,
    pclass: DB.CLASSES.MAGE,
    spec: DB.SPECS.MAGE_FROST,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[10],
    covenant: DB.COVENANTS.KYRIAN,
    pclass: DB.CLASSES.MONK,
    spec: DB.SPECS.MONK_WINDWALKER,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[11],
    covenant: DB.COVENANTS.VENTHYR,
    pclass: DB.CLASSES.PALADIN,
    spec: DB.SPECS.PALADIN_RETRIBUTION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[12],
    covenant: DB.COVENANTS.KYRIAN,
    pclass: DB.CLASSES.PALADIN,
    spec: DB.SPECS.PALADIN_HOLY,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[13],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.PRIEST,
    spec: DB.SPECS.PRIEST_SHADOW,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[14],
    covenant: DB.COVENANTS.VENTHYR,
    pclass: DB.CLASSES.PRIEST,
    spec: DB.SPECS.PRIEST_DISCIPLINE,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[15],
    covenant: DB.COVENANTS.NECROLORD,
    pclass: DB.CLASSES.SHAMAN,
    spec: DB.SPECS.SHAMAN_RESTORATION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[16],
    covenant: DB.COVENANTS.NECROLORD,
    pclass: DB.CLASSES.SHAMAN,
    spec: DB.SPECS.SHAMAN_RESTORATION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[17],
    covenant: DB.COVENANTS.NECROLORD,
    pclass: DB.CLASSES.SHAMAN,
    spec: DB.SPECS.SHAMAN_ELEMENTAL,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[18],
    covenant: DB.COVENANTS.VENTHYR,
    pclass: DB.CLASSES.ROGUE,
    spec: DB.SPECS.ROGUE_ASSASSINATION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[19],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.WARLOCK,
    spec: DB.SPECS.WARLOCK_AFFLICTION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[20],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.WARLOCK,
    spec: DB.SPECS.WARLOCK_AFFLICTION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[21],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.DRUID,
    spec: DB.SPECS.DRUID_RESTORATION,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[22],
    covenant: DB.COVENANTS.NIGHT_FAE,
    pclass: DB.CLASSES.DEMONHUNTER,
    spec: DB.SPECS.DEMONHUNTER_HAVOC,
  },
  {
    id: uuidv4() as RosterCharacterId,
    name: randomNames[23],
    covenant: DB.COVENANTS.NECROLORD,
    pclass: DB.CLASSES.DEATHKNIGHT,
    spec: DB.SPECS.DEATHKNIGHT_UNHOLY,
  },
];

export default randomRoster;
